# Generated by Django 4.2.1 on 2023-06-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='word name', max_length=200, verbose_name='word name')),
                ('dict_info', models.JSONField(help_text='dict info', verbose_name='dict info')),
            ],
            options={
                'db_table': 'words_word_info',
            },
        ),
        migrations.CreateModel(
            name='ProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(help_text='en name', max_length=200, unique=True, verbose_name='en name')),
                ('name', models.CharField(help_text='zh name', max_length=200, verbose_name='zh name')),
                ('words_info', models.ManyToManyField(to='vocabulary.wordinfomodel')),
            ],
            options={
                'db_table': 'words_provider',
            },
        ),
    ]
