# Generated by Django 4.2.1 on 2023-06-02 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='providermodel',
            table='vocabulary_provider',
        ),
        migrations.AlterModelTable(
            name='wordinfomodel',
            table='vocabulary_word_info',
        ),
    ]
