# Generated by Django 4.2.1 on 2023-05-31 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='book name', max_length=200, verbose_name='book name')),
                ('cover', models.CharField(blank=True, max_length=500, null=True, verbose_name='cover name')),
                ('description', models.CharField(max_length=500, verbose_name='')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='create time', verbose_name='create time')),
                ('updated_time', models.DateField(auto_now=True, help_text='update time', verbose_name='update time')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='create time', verbose_name='create time')),
                ('updated_time', models.DateField(auto_now=True, help_text='update time', verbose_name='update time')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ielts.bookmodel')),
            ],
        ),
        migrations.CreateModel(
            name='WordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='word en', max_length=200, verbose_name='word en')),
                ('zh', models.CharField(help_text='word zh', max_length=200, verbose_name='word zh')),
                ('symbol', models.CharField(help_text='word pronounce symbol', max_length=200, verbose_name='word pronounce symbol')),
                ('mp3_file_uuid', models.UUIDField(editable=False, help_text='word en mp3 short url', verbose_name='')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='create time', verbose_name='create time')),
                ('updated_time', models.DateField(auto_now=True, help_text='update time', verbose_name='update time')),
            ],
        ),
        migrations.CreateModel(
            name='PaperModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='paper name')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='create time', verbose_name='create time')),
                ('updated_time', models.DateField(auto_now=True, help_text='update time', verbose_name='update time')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ielts.chaptermodel')),
                ('words', models.ManyToManyField(to='ielts.wordmodel')),
            ],
        ),
    ]
