# Generated by Django 4.2.1 on 2023-05-31 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookmodel',
            table='ielts_book',
        ),
        migrations.AlterModelTable(
            name='chaptermodel',
            table='ielts_chapter',
        ),
        migrations.AlterModelTable(
            name='papermodel',
            table='ielts_paper',
        ),
        migrations.AlterModelTable(
            name='wordmodel',
            table='ielts_word',
        ),
    ]
