# Generated by Django 4.2.1 on 2023-06-01 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0002_alter_bookmodel_table_alter_chaptermodel_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptermodel',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='ielts.bookmodel'),
        ),
        migrations.AlterField(
            model_name='papermodel',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='ielts.chaptermodel'),
        ),
        migrations.AlterField(
            model_name='wordmodel',
            name='mp3_file_uuid',
            field=models.UUIDField(blank=True, editable=False, help_text='word en mp3 short url', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='wordmodel',
            name='symbol',
            field=models.CharField(blank=True, help_text='word pronounce symbol', max_length=200, null=True, verbose_name='word pronounce symbol'),
        ),
        migrations.AlterField(
            model_name='wordmodel',
            name='zh',
            field=models.CharField(blank=True, help_text='word zh', max_length=200, null=True, verbose_name='word zh'),
        ),
    ]
