# Generated by Django 4.2.1 on 2023-06-01 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0003_alter_chaptermodel_book_id_alter_papermodel_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptermodel',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='ielts.bookmodel'),
        ),
        migrations.AlterField(
            model_name='papermodel',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='ielts.chaptermodel'),
        ),
    ]
