# Generated by Django 4.2.1 on 2023-06-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0004_alter_chaptermodel_book_id_alter_papermodel_chapter'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wordmodel',
            table='word',
        ),
    ]
