# Generated by Django 4.2.1 on 2023-06-01 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0005_alter_wordmodel_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordmodel',
            name='mp3_file_uuid',
        ),
        migrations.CreateModel(
            name='Mp3FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_file_uuid', models.UUIDField(blank=True, editable=False, help_text='word en mp3 short url', null=True, verbose_name='')),
                ('zh_file_uuid', models.UUIDField(blank=True, editable=False, help_text='word zh mp3 short url', null=True, verbose_name='')),
                ('mp3_files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ielts.wordmodel')),
            ],
        ),
    ]
