# Generated by Django 4.2.1 on 2023-06-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0006_remove_wordmodel_mp3_file_uuid_mp3filemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='标签', max_length=200, verbose_name='标签')),
                ('words', models.ManyToManyField(to='ielts.wordmodel')),
            ],
        ),
    ]
