# Generated by Django 4.2.1 on 2023-06-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0007_tagmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordmodel',
            name='grammar_info',
            field=models.JSONField(default=1, help_text='grammar info', verbose_name='grammar info'),
            preserve_default=False,
        ),
    ]
