# Generated by Django 4.2.1 on 2023-06-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0008_wordmodel_grammar_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='name',
            field=models.CharField(help_text='标签', max_length=200, unique=True, verbose_name='标签'),
        ),
        migrations.AlterModelTable(
            name='mp3filemodel',
            table='mp3_file',
        ),
        migrations.AlterModelTable(
            name='tagmodel',
            table='tag',
        ),
    ]
