# Generated by Django 4.2.1 on 2023-06-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0009_alter_tagmodel_name_alter_mp3filemodel_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mp3filemodel',
            table='ielts_word_mp3',
        ),
        migrations.AlterModelTable(
            name='tagmodel',
            table='ielts_word_tag',
        ),
        migrations.AlterModelTable(
            name='wordmodel',
            table='ielts_word',
        ),
    ]
