# Generated by Django 4.2.1 on 2023-06-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslateWordDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='word name', max_length=200, verbose_name='word name')),
                ('dict_info', models.JSONField(help_text='dict info', verbose_name='dict info')),
            ],
        ),
        migrations.CreateModel(
            name='TranslateProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='zh name', max_length=200, verbose_name='zh name')),
                ('name_en', models.CharField(help_text='en name', max_length=200, verbose_name='en name')),
                ('words', models.ManyToManyField(to='words.translateworddatamodel')),
            ],
        ),
    ]
