# Generated by Django 4.2.1 on 2023-06-01 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='translateworddatamodel',
            table='words_translate_word_data',
        ),
    ]
