# Generated by Django 4.2.1 on 2023-06-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_alter_translateworddatamodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='translateprovidermodel',
            table='words_translate_provider',
        ),
    ]
