# Generated by Django 4.2.1 on 2023-06-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_alter_translateprovidermodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translateprovidermodel',
            name='name_en',
            field=models.CharField(help_text='en name', max_length=200, unique=True, verbose_name='en name'),
        ),
    ]
