FROM ubuntu:latest

RUN apt update && apt install curl ffmpeg python3 python3-pip -y
# RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup-init.sh 
RUN bash rustup-init.sh -y 
# RUN source "$HOME/.cargo/env"
RUN pip install -U openai-whisper  -i https://mirrors.cloud.tencent.com/pypi/simple

WORKDIR /whisper

CMD ["sleep","999999999999"]